### ISSUE TITLE
How to scrape metrics from not /metrics endpoint?

### ISSUE THREAD

**Issue by witold-gren** [prometheus-community/PushProx#159]
Hey,

I implemented `prometheus-pve-exporter` in my proxmox server. But my entire monitoring is run in external cloud configuration. To provide one endpoint to scrape all metrics from all services run in proxmox in decided to use PushProx. The all configuration works quite well.. but I realised that when I use this this tool then I can not scrape metrics from extra endpoint `/pve` but i must use only endpoint `/metrics`.

It is possible to configure more endpoints to scrape metrics?

```
- job_name: "proxmox"
  proxy_url: <<http://A.B.C.D:XXX>>
  metrics_path: /metrics
  ...
  static_configs:
    - targets: [proxmox.local:9221]
```

when I tried change `metrics_path` to use `/pve` then it not works.. any Idea how I can fix this issue?
